version: 1.0.{build}

image:
- Visual Studio 2017

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true

branches:
  only:
  - dev
  
build_script:
- ps: .\build.ps1
- sh: ./build.sh

test: off
artifacts:
- path: artifacts/packages/*.nupkg

deploy:
- provider: NuGet
  server: https://www.myget.org/F/identity/
  api_key:
    secure: 43SK7fLJcrno252Wqb6j+jFYeTjaHG8EWXruhHv6kW+bbySa4uBGTPNFjA7lzD0Y
  skip_symbols: true
  on:
    branch: dev